# -*- coding: utf-8 -*-
"""
Sign Language A-Z  --  Live Webcam Prediction + Text-to-Speech
===============================================================
Uses MediaPipe Hands + the trained MLP model to recognise
ASL alphabet signs (A-Z) from your webcam in real time,
with integrated pyttsx3 text-to-speech output.

Temporal Logic (prevents duplicate letters):
  - 20-frame majority voting (>80% consistency required)
  - 90% model confidence threshold
  - 1.5-second hold timer before committing a letter
  - Hand-reset lock: must remove hand or show a different sign
    before the same letter can be added again

Text-to-Speech:
  - pyttsx3 engine (singleton, non-blocking via background thread)
  - ENTER speaks the full sentence buffer
  - Duplicate speech protection while TTS is active
  - Real-time status display: READY / SPEAKING / COMPLETED
  - AUTO_CLEAR option to clear sentence after speaking

Controls:
  Q / ESC   -> Quit
  C         -> Clear word buffer AND sentence buffer
  SPACE     -> Finish current word, push to sentence buffer
  BKSP      -> Delete last character from word buffer
  ENTER     -> Speak the accumulated sentence aloud

Requirements:
  - models/mlp_model.pkl
  - models/label_encoder.pkl
  - models/scaler.pkl
  (Generated by train_mlp.py)
  - pyttsx3  (pip install pyttsx3)
"""

# ── Suppress noisy logs ────────────────────────────────────────────────────
import os, warnings

os.environ["GLOG_minloglevel"] = "3"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")

# ── Imports ─────────────────────────────────────────────────────────────────
import sys
import time
import threading
import numpy as np
import cv2
import mediapipe as mp
import joblib
import pyttsx3
import pythoncom
from collections import deque, Counter

# ── Paths ───────────────────────────────────────────────────────────────────
MODEL_PATH = os.path.join("models", "mlp_model.pkl")
ENCODER_PATH = os.path.join("models", "label_encoder.pkl")
SCALER_PATH = os.path.join("models", "scaler.pkl")

# ── Temporal Logic Configuration ────────────────────────────────────────────
HISTORY_SIZE = 20             # Number of frames to keep in prediction history
CONSISTENCY_THRESHOLD = 0.80  # >80% of history must agree for a "stable" prediction
CONFIDENCE_THRESHOLD = 0.90   # Model confidence must exceed 90%
HOLD_TIME_REQUIRED = 1.5      # Seconds the prediction must be held before committing
FEEDBACK_DISPLAY_DURATION = 1.0  # Seconds to show "Added X" confirmation

# ── TTS Configuration ──────────────────────────────────────────────────────
TTS_SPEECH_RATE = 150         # Words per minute
TTS_VOLUME = 1.0              # 0.0 to 1.0
AUTO_CLEAR = True             # Clear sentence buffer automatically after speaking

# ── Colours (BGR) ───────────────────────────────────────────────────────────
BG_DARK = (30, 30, 46)        # dark panel background
TEAL = (208, 194, 0)          # teal accent  (#00C2D0)
TEAL_LIGHT = (220, 220, 80)   # lighter teal
WHITE = (255, 255, 255)
GREEN = (100, 220, 100)
RED = (80, 80, 255)
YELLOW = (60, 220, 255)
GRAY = (160, 160, 160)
ORANGE = (50, 160, 255)
CYAN = (255, 255, 0)
PURPLE = (200, 100, 200)


# ═══════════════════════════════════════════════════════════════════════════
# Translation Engine (modular stub for future language support)
# ═══════════════════════════════════════════════════════════════════════════

class TranslationEngine:
    """
    Modular translation component for future multilingual TTS support.

    Currently acts as a pass-through (English → English). To enable
    Tamil translation in the future, implement the translate() method
    using googletrans, deep-translator, or a local model.

    Usage:
        translator = TranslationEngine(target_lang="ta")
        tamil_text = translator.translate("HELLO")  # → "வணக்கம்"
    """

    # Predefined dictionary for common ASL words → Tamil
    # This avoids API calls for frequently used phrases
    TAMIL_DICT = {
        "HELLO": "வணக்கம்",
        "THANK YOU": "நன்றி",
        "PLEASE": "தயவுசெய்து",
        "YES": "ஆம்",
        "NO": "இல்லை",
        "GOODBYE": "போய் வருகிறேன்",
        "SORRY": "மன்னிக்கவும்",
        "HELP": "உதவி",
        "I LOVE YOU": "நான் உன்னை காதலிக்கிறேன்",
    }

    def __init__(self, target_lang="en", enabled=False):
        """
        Args:
            target_lang: ISO 639-1 language code ("en", "ta", etc.)
            enabled: Set True to activate translation. False = pass-through.
        """
        self.target_lang = target_lang
        self.enabled = enabled

    def translate(self, text: str) -> str:
        """
        Translate the input text to the target language.

        Currently returns the original text unchanged.
        Override this method for actual translation.
        """
        if not self.enabled or self.target_lang == "en":
            return text

        # Check local dictionary first (for Tamil)
        if self.target_lang == "ta":
            upper_text = text.upper().strip()
            if upper_text in self.TAMIL_DICT:
                return self.TAMIL_DICT[upper_text]

        # Placeholder for API-based translation
        # Future: from deep_translator import GoogleTranslator
        # return GoogleTranslator(source='en', target=self.target_lang).translate(text)
        return text


# ═══════════════════════════════════════════════════════════════════════════
# Speech Engine (persistent worker thread + queue architecture)
# ═══════════════════════════════════════════════════════════════════════════

import queue  # stdlib, for thread-safe speech request passing


class SpeechEngine:
    """
    Production-grade TTS wrapper using pyttsx3.

    Architecture:
      Spawns a fresh pyttsx3 engine in a temporary background thread for every
      single speech request. The engine is created, used, and destroyed
      entirely within that thread.

    Why this design?
      Creating a fresh engine and destroying it after speech prevents COM/SAPI5
      state corruption and ensures unlimited consecutive speech requests work
      consistently on Windows.

    Status lifecycle:
      READY → speak() called → SPEAKING → audio finishes → COMPLETED
            → (auto 2s) → READY
    """

    _instance = None
    _init_lock = threading.Lock()

    # Speech status constants
    STATUS_READY = "READY"
    STATUS_SPEAKING = "SPEAKING"
    STATUS_COMPLETED = "COMPLETED"

    def __new__(cls):
        """Singleton: ensure only one SpeechEngine instance exists."""
        with cls._init_lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        """Initialize the speech engine interface (runs only once)."""
        if self._initialized:
            return
        self._initialized = True

        # Thread-safe state tracking
        self._status_lock = threading.Lock()
        self._status = self.STATUS_READY
        self._is_speaking_val = False
        self._current_text = ""
        self._completed_timestamp = 0.0
        self._completed_display_duration = 2.0  # Show COMPLETED for 2s
        self._auto_cleared = False  # One-shot flag for auto-clear

        # Engine-available flag for compatibility
        self._engine_ready = threading.Event()
        self._engine_ready.set()

        print("[OK] TTS engine interface initialized.")

    def _speak_thread(self, text):
        """Background thread: handles SAPI5 COM apartment, engine init, speech, and destruction."""
        import pythoncom
        pythoncom.CoInitialize()
        engine = None
        try:
            print("[DEBUG] Engine Created")
            engine = pyttsx3.init()
            engine.setProperty("rate", TTS_SPEECH_RATE)
            engine.setProperty("volume", TTS_VOLUME)

            print("[DEBUG] Speech Started")
            engine.say(text)
            engine.runAndWait()
            print("[DEBUG] Speech Finished")

        except Exception as e:
            print(f"[ERROR] Exception during speech execution: {e}")
        finally:
            if engine is not None:
                try:
                    engine.stop()
                except Exception:
                    pass
                del engine
                print("[DEBUG] Engine Destroyed")

            pythoncom.CoUninitialize()

            # Always update status and release speaking lock
            with self._status_lock:
                self._is_speaking_val = False
                self._auto_cleared = False
                self._status = self.STATUS_COMPLETED
                self._completed_timestamp = time.time()
            print("[DEBUG] Status Reset")

    # ── Public API (called from the main/UI thread) ─────────────────────

    @property
    def status(self) -> str:
        """Current speech status: READY, SPEAKING, or COMPLETED."""
        with self._status_lock:
            # Auto-transition COMPLETED → READY after the display duration
            if (self._status == self.STATUS_COMPLETED
                    and time.time() - self._completed_timestamp
                    > self._completed_display_duration):
                self._status = self.STATUS_READY
            return self._status

    @property
    def is_speaking(self) -> bool:
        """True if TTS is currently producing audio."""
        with self._status_lock:
            return self._is_speaking_val

    @property
    def just_completed(self) -> bool:
        """
        True ONCE after speech finishes, for triggering auto-clear.
        Calling this consumes the flag (one-shot).
        """
        with self._status_lock:
            if (self._status == self.STATUS_COMPLETED
                    and not self._auto_cleared):
                self._auto_cleared = True
                return True
            return False

    def speak(self, text: str) -> bool:
        """
        Submit a speech request by spawning a new background thread.

        Returns True if the request was accepted, False if rejected
        (empty text or already speaking).
        """
        print("[DEBUG] speak() called")
        if not text or not text.strip():
            print("[TTS] No text to speak.")
            return False

        # Reject if already speaking (prevents overlapping speech)
        if self.is_speaking:
            with self._status_lock:
                print(f"[DEBUG] Status: {self.status}")
                print(f"[DEBUG] Current Text Being Spoken:\n{self._current_text}")
            print("[TTS] Already speaking, ignoring request.")
            return False

        clean_text = text.strip()

        # Lock state and set active text before launching thread
        with self._status_lock:
            self._status = self.STATUS_SPEAKING
            self._is_speaking_val = True
            self._current_text = clean_text
            self._auto_cleared = False

        print("[DEBUG] Queue Accepted")
        print(f"[DEBUG] Status: {self.status}")

        # Launch speech in background thread (Fix 9)
        t = threading.Thread(
            target=self._speak_thread,
            args=(clean_text,),
            name="TTS-Request-Thread",
            daemon=True
        )
        t.start()

        return True

    def shutdown(self):
        """Shutdown helper (noop in this design, for compatibility)."""
        pass


# ═══════════════════════════════════════════════════════════════════════════
# Model & Feature Extraction
# ═══════════════════════════════════════════════════════════════════════════

def load_model():
    """Load the trained MLP model, label encoder, and scaler."""
    for path in (MODEL_PATH, ENCODER_PATH, SCALER_PATH):
        if not os.path.exists(path):
            print(f"[ERROR] Missing file: {path}")
            print("        Run train_mlp.py first to generate model artefacts.")
            sys.exit(1)

    model = joblib.load(MODEL_PATH)
    le = joblib.load(ENCODER_PATH)
    scaler = joblib.load(SCALER_PATH)
    print("[OK] Model, encoder, and scaler loaded.")
    return model, le, scaler


def extract_landmarks(hand_landmarks) -> np.ndarray:
    """Convert MediaPipe hand landmarks to a flat 63-element array."""
    coords = []
    for lm in hand_landmarks.landmark:
        coords.extend([lm.x, lm.y, lm.z])
    return np.array(coords, dtype=np.float32).reshape(1, -1)


# ═══════════════════════════════════════════════════════════════════════════
# HUD Drawing Utilities
# ═══════════════════════════════════════════════════════════════════════════

def draw_rounded_rect(img, pt1, pt2, color, radius=18, thickness=-1, alpha=0.7):
    """Draw a filled rounded rectangle with transparency."""
    overlay = img.copy()
    x1, y1 = pt1
    x2, y2 = pt2

    # Draw rectangle body
    cv2.rectangle(overlay, (x1 + radius, y1), (x2 - radius, y2), color, thickness)
    cv2.rectangle(overlay, (x1, y1 + radius), (x2, y2 - radius), color, thickness)

    # Draw corners
    cv2.ellipse(overlay, (x1 + radius, y1 + radius), (radius, radius), 180, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x2 - radius, y1 + radius), (radius, radius), 270, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x1 + radius, y2 - radius), (radius, radius), 90, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x2 - radius, y2 - radius), (radius, radius), 0, 0, 90, color, thickness)

    cv2.addWeighted(overlay, alpha, img, 1 - alpha, 0, img)


def draw_confidence_bar(img, x, y, w, h, confidence, color):
    """Draw a sleek confidence bar."""
    # Background bar
    cv2.rectangle(img, (x, y), (x + w, y + h), (50, 50, 60), -1)
    cv2.rectangle(img, (x, y), (x + w, y + h), (80, 80, 90), 1)
    # Filled portion
    fill_w = int(w * confidence)
    if fill_w > 0:
        cv2.rectangle(img, (x + 1, y + 1), (x + fill_w - 1, y + h - 1), color, -1)


def draw_hold_progress_bar(img, x, y, w, h, progress, color):
    """Draw an animated hold-time progress bar with a glow effect."""
    # Background track
    cv2.rectangle(img, (x, y), (x + w, y + h), (40, 40, 50), -1)
    cv2.rectangle(img, (x, y), (x + w, y + h), (70, 70, 80), 1)

    fill_w = int(w * min(progress, 1.0))
    if fill_w > 0:
        # Main fill
        cv2.rectangle(img, (x + 1, y + 1), (x + fill_w - 1, y + h - 1), color, -1)
        # Bright leading edge (glow)
        edge_x = x + fill_w - 1
        if edge_x > x + 2:
            cv2.line(img, (edge_x, y + 1), (edge_x, y + h - 1), WHITE, 1)


def draw_hud(frame, prediction, confidence, probabilities, label_names,
             word_buffer, sentence_buffer, fps, hand_detected, state,
             speech_status):
    """
    Draw a polished heads-up display overlay.

    The `state` dict provides temporal-logic feedback:
      - stable_prediction: the majority-voted prediction (or None)
      - hold_elapsed: seconds held so far (0.0 if not holding)
      - is_holding: True if currently counting down the hold timer
      - locked_until_reset: True if waiting for hand-reset
      - feedback_message: e.g. "Added A" (or None)
    """
    h, w = frame.shape[:2]

    # ── Top-left: Title bar ─────────────────────────────────────────────────
    draw_rounded_rect(frame, (10, 10), (420, 55), BG_DARK, radius=12, alpha=0.85)
    cv2.putText(frame, "ASL Sign Language", (24, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, TEAL, 2, cv2.LINE_AA)
    cv2.putText(frame, f"FPS: {fps:.0f}", (280, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, GRAY, 1, cv2.LINE_AA)

    # Speech status indicator (top bar, right of FPS)
    if speech_status == SpeechEngine.STATUS_SPEAKING:
        status_color = ORANGE
        status_icon = ">> SPEAKING"
    elif speech_status == SpeechEngine.STATUS_COMPLETED:
        status_color = GREEN
        status_icon = "DONE"
    else:
        status_color = GRAY
        status_icon = "TTS READY"
    cv2.putText(frame, status_icon, (340, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38, status_color, 1, cv2.LINE_AA)

    # ── Main prediction panel (right side) ──────────────────────────────────
    panel_x = w - 280
    panel_y = 10
    panel_w = 270
    panel_h = 360
    draw_rounded_rect(frame, (panel_x, panel_y),
                      (panel_x + panel_w, panel_y + panel_h),
                      BG_DARK, radius=14, alpha=0.85)

    if hand_detected and prediction:
        # Prediction letter — large
        letter_size = cv2.getTextSize(prediction, cv2.FONT_HERSHEY_SIMPLEX, 3.0, 4)[0]
        letter_x = panel_x + (panel_w - letter_size[0]) // 2
        cv2.putText(frame, prediction, (letter_x, panel_y + 80),
                    cv2.FONT_HERSHEY_SIMPLEX, 3.0, TEAL, 4, cv2.LINE_AA)

        # Confidence percentage
        conf_text = f"{confidence * 100:.1f}%"
        conf_color = GREEN if confidence > 0.85 else YELLOW if confidence > 0.5 else RED
        conf_size = cv2.getTextSize(conf_text, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)[0]
        conf_x = panel_x + (panel_w - conf_size[0]) // 2
        cv2.putText(frame, conf_text, (conf_x, panel_y + 110),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, conf_color, 2, cv2.LINE_AA)

        # Confidence bar
        draw_confidence_bar(frame, panel_x + 20, panel_y + 120,
                            panel_w - 40, 14, confidence, conf_color)

        # ── Hold-time progress (temporal feedback) ──────────────────────────
        y_hold = panel_y + 150
        if state["is_holding"]:
            elapsed = state["hold_elapsed"]
            progress = elapsed / HOLD_TIME_REQUIRED
            hold_text = f"Hold: {elapsed:.1f} / {HOLD_TIME_REQUIRED:.1f}s"
            # Color transitions from orange → green as progress increases
            bar_color = GREEN if progress > 0.8 else ORANGE
            cv2.putText(frame, hold_text, (panel_x + 15, y_hold),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.48, YELLOW, 1, cv2.LINE_AA)
            draw_hold_progress_bar(frame, panel_x + 20, y_hold + 6,
                                   panel_w - 40, 12, progress, bar_color)
            y_hold += 32
        elif state["locked_until_reset"]:
            cv2.putText(frame, "Locked (change sign or remove hand)",
                        (panel_x + 12, y_hold),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.35, GRAY, 1, cv2.LINE_AA)
            y_hold += 22
        elif confidence < CONFIDENCE_THRESHOLD:
            cv2.putText(frame, f"Low confidence (<{CONFIDENCE_THRESHOLD*100:.0f}%)",
                        (panel_x + 12, y_hold),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.38, RED, 1, cv2.LINE_AA)
            y_hold += 22
        else:
            y_hold += 5  # small gap

        # ── Top-3 predictions ───────────────────────────────────────────────
        top_indices = np.argsort(probabilities)[::-1][:3]
        y_offset = y_hold + 10
        cv2.putText(frame, "Top Predictions:", (panel_x + 15, y_offset),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, GRAY, 1, cv2.LINE_AA)
        y_offset += 28
        for rank, idx in enumerate(top_indices, 1):
            lbl = label_names[idx]
            prob = probabilities[idx]
            bar_color = TEAL if rank == 1 else TEAL_LIGHT
            text = f"{rank}. {lbl}"
            cv2.putText(frame, text, (panel_x + 15, y_offset),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, WHITE, 1, cv2.LINE_AA)
            draw_confidence_bar(frame, panel_x + 60, y_offset - 10,
                                panel_w - 90, 10, prob, bar_color)
            pct = f"{prob * 100:.1f}%"
            cv2.putText(frame, pct, (panel_x + panel_w - 55, y_offset),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.38, GRAY, 1, cv2.LINE_AA)
            y_offset += 28
    else:
        # No hand detected
        msg = "No Hand Detected"
        msg_size = cv2.getTextSize(msg, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)[0]
        msg_x = panel_x + (panel_w - msg_size[0]) // 2
        cv2.putText(frame, msg, (msg_x, panel_y + 100),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, GRAY, 2, cv2.LINE_AA)

        hint = "Show your hand"
        hint_size = cv2.getTextSize(hint, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)[0]
        hint_x = panel_x + (panel_w - hint_size[0]) // 2
        cv2.putText(frame, hint, (hint_x, panel_y + 135),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, GRAY, 1, cv2.LINE_AA)

    # ── Feedback banner (e.g. "Added A") ────────────────────────────────────
    if state["feedback_message"]:
        fb_text = state["feedback_message"]
        fb_size = cv2.getTextSize(fb_text, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2)[0]
        fb_x = (w - fb_size[0]) // 2
        fb_y = h // 2 - 40
        draw_rounded_rect(frame, (fb_x - 20, fb_y - 35),
                          (fb_x + fb_size[0] + 20, fb_y + 15),
                          (20, 100, 20), radius=14, alpha=0.85)
        cv2.putText(frame, fb_text, (fb_x, fb_y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, GREEN, 2, cv2.LINE_AA)

    # ── Sentence buffer (second-from-bottom bar) ────────────────────────────
    sent_bar_h = 45
    sent_bar_y = h - 55 - 10 - sent_bar_h - 8
    draw_rounded_rect(frame, (10, sent_bar_y), (w - 10, sent_bar_y + sent_bar_h),
                      BG_DARK, radius=12, alpha=0.80)

    cv2.putText(frame, "Sentence:", (24, sent_bar_y + 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.48, PURPLE, 1, cv2.LINE_AA)

    sentence_text = " ".join(sentence_buffer) if sentence_buffer else "(press SPACE to finish words)"
    sent_color = WHITE if sentence_buffer else GRAY
    cv2.putText(frame, sentence_text, (120, sent_bar_y + 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, sent_color, 1, cv2.LINE_AA)

    # ── Word buffer (bottom bar) ────────────────────────────────────────────
    bar_h = 55
    bar_y = h - bar_h - 10
    draw_rounded_rect(frame, (10, bar_y), (w - 10, bar_y + bar_h),
                      BG_DARK, radius=12, alpha=0.85)

    cv2.putText(frame, "Word:", (24, bar_y + 35),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, GRAY, 1, cv2.LINE_AA)

    word_text = "".join(word_buffer) if word_buffer else "_"
    cv2.putText(frame, word_text, (90, bar_y + 36),
                cv2.FONT_HERSHEY_SIMPLEX, 0.75, WHITE, 2, cv2.LINE_AA)

    # Controls hint
    controls = "[Q]Quit [C]Clear [SPC]Word [BKSP]Del [ENTER]Speak"
    cv2.putText(frame, controls, (w - 460, bar_y + 36),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38, GRAY, 1, cv2.LINE_AA)


# ── Temporal Logic Engine ───────────────────────────────────────────────────

def get_majority_prediction(history, consistency_threshold):
    """
    Analyse the prediction history using majority voting.

    Returns (letter, ratio) if the most common prediction exceeds the
    consistency threshold, otherwise (None, 0.0).
    """
    if len(history) < history.maxlen:
        # Not enough history accumulated yet
        return None, 0.0

    counter = Counter(history)
    most_common_letter, count = counter.most_common(1)[0]
    ratio = count / len(history)

    if ratio >= consistency_threshold:
        return most_common_letter, ratio
    return None, ratio


# ═══════════════════════════════════════════════════════════════════════════
# Main Application Loop
# ═══════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "=" * 58)
    print("  ASL Sign Language - Live Prediction + Text-to-Speech")
    print("=" * 58)

    # ── Load model ──────────────────────────────────────────────────────────
    model, le, scaler = load_model()
    label_names = le.classes_

    # ── Initialize TTS engine (singleton) ───────────────────────────────────
    tts = SpeechEngine()

    # ── Initialize translation engine (disabled by default) ─────────────────
    # To enable Tamil: TranslationEngine(target_lang="ta", enabled=True)
    translator = TranslationEngine(target_lang="en", enabled=False)

    # ── MediaPipe Hands ─────────────────────────────────────────────────────
    mp_hands = mp.solutions.hands
    mp_draw = mp.solutions.drawing_utils
    mp_styles = mp.solutions.drawing_styles

    hands = mp_hands.Hands(
        static_image_mode=False,
        max_num_hands=1,
        min_detection_confidence=0.7,
        min_tracking_confidence=0.5,
    )

    # ── Webcam ──────────────────────────────────────────────────────────────
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("[ERROR] Cannot open webcam.")
        sys.exit(1)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    print("[OK] Webcam opened. Press Q or ESC to quit.\n")

    # ── State Variables (Temporal Logic) ────────────────────────────────────
    word_buffer = deque(maxlen=50)       # Current word being built letter-by-letter
    sentence_buffer = []                 # Accumulated words (list of strings)

    # Per-frame prediction output
    current_prediction = None            # Raw prediction from model this frame
    confidence = 0.0                     # Raw confidence from model this frame
    probabilities = np.zeros(len(label_names))

    # Prediction history for majority voting (last 20 frames)
    prediction_history = deque(maxlen=HISTORY_SIZE)

    # Hold timer: tracks when a stable prediction first appeared
    hold_timer_start = None              # time.time() when hold began, None if not holding

    # Lock state: prevents re-adding the same letter
    last_added_letter = None             # The last letter successfully committed
    locked_until_reset = False           # True = waiting for hand removal or new sign

    # Feedback overlay
    feedback_message = None              # e.g. "Added A"
    feedback_timestamp = 0.0             # time.time() when feedback was set

    # FPS tracking
    prev_time = time.time()
    fps = 0.0

    print("[STATE] Temporal logic engine active:")
    print(f"        History window:   {HISTORY_SIZE} frames")
    print(f"        Consistency:      >{CONSISTENCY_THRESHOLD*100:.0f}%")
    print(f"        Confidence:       >={CONFIDENCE_THRESHOLD*100:.0f}%")
    print(f"        Hold time:        {HOLD_TIME_REQUIRED}s")
    print(f"        Auto-clear:       {AUTO_CLEAR}\n")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("[WARN] Failed to read frame, retrying...")
            continue

        frame = cv2.flip(frame, 1)  # mirror for natural interaction
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = hands.process(rgb)

        hand_detected = False
        now = time.time()

        # ── Expire feedback message after FEEDBACK_DISPLAY_DURATION ──────
        if feedback_message and (now - feedback_timestamp) > FEEDBACK_DISPLAY_DURATION:
            feedback_message = None

        # ── Auto-clear sentence buffer after speech completes ────────────
        # Uses the one-shot `just_completed` flag to fire exactly once,
        # preventing repeated clears every frame during the COMPLETED window.
        if AUTO_CLEAR and tts.just_completed and sentence_buffer:
            sentence_buffer.clear()
            print("[AUTO-CLEAR] Sentence buffer cleared after speech.")

        # ================================================================
        # HAND DETECTED → run prediction + temporal logic
        # ================================================================
        if results.multi_hand_landmarks:
            hand_detected = True
            hand_lm = results.multi_hand_landmarks[0]

            # Draw hand landmarks with styled connections
            mp_draw.draw_landmarks(
                frame, hand_lm, mp_hands.HAND_CONNECTIONS,
                mp_styles.get_default_hand_landmarks_style(),
                mp_styles.get_default_hand_connections_style(),
            )

            # Extract features & predict
            features = extract_landmarks(hand_lm)
            features_scaled = scaler.transform(features)

            current_prediction = le.inverse_transform(model.predict(features_scaled))[0]
            probabilities = model.predict_proba(features_scaled)[0]
            confidence = float(np.max(probabilities))

            # ── Step 1: Append to prediction history ────────────────────
            prediction_history.append(current_prediction)

            # ── Step 2: Majority voting ─────────────────────────────────
            stable_prediction, consistency_ratio = get_majority_prediction(
                prediction_history, CONSISTENCY_THRESHOLD
            )

            # ── Step 3: Temporal decision logic ─────────────────────────
            if stable_prediction is not None and confidence >= CONFIDENCE_THRESHOLD:
                # We have a consistent, high-confidence prediction

                # Check if locked: same letter was just added
                if locked_until_reset and stable_prediction == last_added_letter:
                    # LOCKED: user must remove hand or change sign
                    hold_timer_start = None  # don't accumulate hold time

                elif stable_prediction != last_added_letter:
                    # NEW LETTER detected (different from the locked one)
                    # This automatically unlocks the system
                    locked_until_reset = False

                    if hold_timer_start is None:
                        # Start the hold timer for this new stable prediction
                        hold_timer_start = now
                    else:
                        # Check if held long enough
                        hold_elapsed = now - hold_timer_start
                        if hold_elapsed >= HOLD_TIME_REQUIRED:
                            # ── COMMIT THE LETTER ───────────────────────
                            word_buffer.append(stable_prediction)
                            last_added_letter = stable_prediction
                            locked_until_reset = True
                            hold_timer_start = None

                            # Set feedback
                            feedback_message = f"Added: {stable_prediction}"
                            feedback_timestamp = now

                            print(f"[COMMIT] '{stable_prediction}' added. "
                                  f"Word: {''.join(word_buffer)}")

                else:
                    # Same letter, but not locked (first occurrence)
                    if hold_timer_start is None:
                        hold_timer_start = now
                    else:
                        hold_elapsed = now - hold_timer_start
                        if hold_elapsed >= HOLD_TIME_REQUIRED:
                            # ── COMMIT THE LETTER ───────────────────────
                            word_buffer.append(stable_prediction)
                            last_added_letter = stable_prediction
                            locked_until_reset = True
                            hold_timer_start = None

                            feedback_message = f"Added: {stable_prediction}"
                            feedback_timestamp = now

                            print(f"[COMMIT] '{stable_prediction}' added. "
                                  f"Word: {''.join(word_buffer)}")
            else:
                # Prediction is unstable or low-confidence: reset hold timer
                hold_timer_start = None

        # ================================================================
        # NO HAND DETECTED → reset all temporal state
        # ================================================================
        else:
            current_prediction = None
            confidence = 0.0
            prediction_history.clear()
            hold_timer_start = None

            # Hand removal resets the lock, allowing the same letter next time
            if locked_until_reset:
                locked_until_reset = False
                last_added_letter = None
                print("[RESET] Hand removed — lock cleared.")

        # ── Compute HUD state dict ──────────────────────────────────────
        hold_elapsed = 0.0
        is_holding = False
        if hold_timer_start is not None:
            hold_elapsed = now - hold_timer_start
            is_holding = True

        hud_state = {
            "stable_prediction": current_prediction,
            "hold_elapsed": hold_elapsed,
            "is_holding": is_holding,
            "locked_until_reset": locked_until_reset,
            "feedback_message": feedback_message,
        }

        # ── FPS ─────────────────────────────────────────────────────────
        fps = 0.8 * fps + 0.2 * (1.0 / max(now - prev_time, 1e-6))
        prev_time = now

        # ── Draw HUD ────────────────────────────────────────────────────
        draw_hud(frame, current_prediction, confidence, probabilities,
                 label_names, word_buffer, sentence_buffer, fps,
                 hand_detected, hud_state, tts.status)

        cv2.imshow("ASL Sign Language Recognition", frame)

        # ── Key handling ────────────────────────────────────────────────
        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), ord("Q"), 27):  # Q or ESC
            break

        elif key in (ord("c"), ord("C")):
            # Clear BOTH word buffer and sentence buffer
            word_buffer.clear()
            sentence_buffer.clear()
            last_added_letter = None
            locked_until_reset = False
            print("[CLEAR] Word + sentence buffers cleared.")

        elif key == 32:  # SPACE — finish current word and push to sentence
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                print(f"[WORD] \"{current_word}\" added to sentence. "
                      f"Sentence: {' '.join(sentence_buffer)}")
            word_buffer.clear()
            last_added_letter = None
            locked_until_reset = False

        elif key == 8:  # BACKSPACE
            if word_buffer:
                removed = word_buffer.pop()
                print(f"[BKSP] Removed '{removed}'.")
                last_added_letter = None
                locked_until_reset = False

        elif key == 13:  # ENTER — speak the sentence
            print("[DEBUG] ENTER PRESSED")
            # If there's an unfinished word in the buffer, include it
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                word_buffer.clear()

            if sentence_buffer:
                full_sentence = " ".join(sentence_buffer)
                print(f"[DEBUG] Text:\n{full_sentence}")
                # Apply translation (pass-through by default)
                translated = translator.translate(full_sentence)
                spoken = tts.speak(translated)
                print(f"[DEBUG] speak() returned:\n{spoken}")
                if spoken:
                    feedback_message = f"Speaking: {translated}"
                    feedback_timestamp = now
            else:
                print("[TTS] No text available to speak.")
                feedback_message = "No text to speak"
                feedback_timestamp = now

    # ── Cleanup ─────────────────────────────────────────────────────────────
    tts.shutdown()
    hands.close()
    cap.release()
    cv2.destroyAllWindows()
    final_word = "".join(word_buffer) if word_buffer else "(empty)"
    final_sentence = " ".join(sentence_buffer) if sentence_buffer else "(empty)"
    print(f"\n[OK] Session ended.")
    print(f"     Final word:     {final_word}")
    print(f"     Final sentence: {final_sentence}")


if __name__ == "__main__":
    main()
