# -*- coding: utf-8 -*-
"""
Sign Language A-Z  --  Live Webcam Prediction + Text-to-Speech
===============================================================
Uses MediaPipe Hands + the trained MLP model to recognise
ASL alphabet signs (A-Z) from your webcam in real time,
with integrated pyttsx3 text-to-speech output.

Temporal Logic (prevents duplicate letters):
  - 20-frame majority voting (>80% consistency required)
  - 90% model confidence threshold
  - 0.5-second hold timer before committing a letter
  - Hand-reset lock: must remove hand or show a different sign
    before the same letter can be added again

Text-to-Speech:
  - pyttsx3 engine (singleton, non-blocking via background thread)
  - ENTER speaks the full sentence buffer
  - Duplicate speech protection while TTS is active
  - Real-time status display: READY / SPEAKING / COMPLETED
  - AUTO_CLEAR option to clear sentence after speaking

Bilingual Support (English / Tamil):
  - L key toggles between English and Tamil modes
  - Tamil mode: translates recognised text and displays in Tamil
  - Tamil TTS voice selection (falls back to English if unavailable)
  - Future-ready architecture: add Hindi, Telugu, Malayalam, etc.

Controls:
  Q / ESC   -> Quit
  C         -> Clear word buffer AND sentence buffer
  L         -> Toggle language (English <-> Tamil)
  SPACE     -> Finish current word, push to sentence buffer
  BKSP      -> Delete last character from word buffer
  ENTER     -> Speak the accumulated sentence aloud

Requirements:
  - models/mlp_model.pkl
  - models/label_encoder.pkl
  - models/scaler.pkl
  (Generated by train_mlp.py)
  - pyttsx3  (pip install pyttsx3)
  - Pillow   (pip install Pillow, optional for Tamil text display)
"""

# ── Suppress noisy logs ────────────────────────────────────────────────────
import os, warnings

os.environ["GLOG_minloglevel"] = "3"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")

# ── Monkeypatch httpcore for googletrans compatibility ──────────────────────
import httpcore
if not hasattr(httpcore, "SyncHTTPTransport"):
    class DummySyncHTTPTransport:
        pass
    httpcore.SyncHTTPTransport = DummySyncHTTPTransport

# ── Imports ─────────────────────────────────────────────────────────────────
import sys
import time
import functools
import threading
import numpy as np
import cv2
import mediapipe as mp
import joblib
import pyttsx3
import pythoncom
from collections import deque, Counter
from supabase_client import SupabaseManager
from utils import extract_enhanced_features  # Enhanced landmarks and engineered features

# ── Optional: PIL for Unicode (Tamil) text rendering ────────────────────
try:
    from PIL import Image, ImageDraw, ImageFont
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    print("[WARN] PIL/Pillow not installed. Tamil text display will use fallback.")
    print("       Install with: pip install Pillow")

# ── Paths ───────────────────────────────────────────────────────────────────
MODEL_PATH = os.path.join("models", "mlp_model.pkl")
ENCODER_PATH = os.path.join("models", "label_encoder.pkl")
SCALER_PATH = os.path.join("models", "scaler.pkl")

# Compatibility / Feature mode indicator
MODEL_EXPECTS_ENHANCED = False

# ── Temporal Logic Configuration ────────────────────────────────────────────
HISTORY_SIZE = 20             # Number of frames to keep in prediction history
CONSISTENCY_THRESHOLD = 0.80  # >80% of history must agree for a "stable" prediction
CONFIDENCE_THRESHOLD = 0.95   # Model confidence must exceed 95%
HOLD_TIME_REQUIRED = 0.5      # Seconds the prediction must be held before committing
FEEDBACK_DISPLAY_DURATION = 1.0  # Seconds to show "Added X" confirmation

# ── TTS Configuration ──────────────────────────────────────────────────────
TTS_SPEECH_RATE = 150         # Words per minute
TTS_VOLUME = 1.0              # 0.0 to 1.0
AUTO_CLEAR = True             # Clear sentence buffer automatically after speaking

# ── Colours (BGR) ───────────────────────────────────────────────────────────
BG_DARK = (30, 30, 46)        # dark panel background
TEAL = (208, 194, 0)          # teal accent  (#00C2D0)
TEAL_LIGHT = (220, 220, 80)   # lighter teal
WHITE = (255, 255, 255)
GREEN = (100, 220, 100)
RED = (80, 80, 255)
YELLOW = (60, 220, 255)
GRAY = (160, 160, 160)
ORANGE = (50, 160, 255)
CYAN = (255, 255, 0)
PURPLE = (200, 100, 200)


# ═══════════════════════════════════════════════════════════════════════════
# Language Configuration (future-ready: add new languages here)
# ═══════════════════════════════════════════════════════════════════════════

LANGUAGE_CONFIG = {
    "English": {"code": "en", "name_en": "English", "name_native": "English"},
    "Tamil": {"code": "ta", "name_en": "Tamil", "name_native": "தமிழ்"},
}

AVAILABLE_LANGUAGES = list(LANGUAGE_CONFIG.keys())

# ── Emergency Configuration ──────────────────────────────────────────────────
EMERGENCY_KEYWORDS = {
    "English": ["HELP", "EMERGENCY", "DOCTOR", "AMBULANCE", "MEDICINE", "HOSPITAL", "PAIN", "ACCIDENT", "DANGER", "FIRE"],
    "Tamil": ["உதவி", "அவசரம்", "மருத்துவர்", "ஆம்புலன்ஸ்", "மருத்துவமனை", "வலி", "விபத்து", "ஆபத்து", "தீ"]
}

def is_emergency_text(text: str) -> str | None:
    """
    Checks if text (case-insensitive) contains any of the emergency keywords.
    Returns the matched keyword if found, otherwise None.
    """
    if not text:
        return None
    
    # Check English keywords (tokenized comparison)
    tokens = [t.upper().strip() for t in text.split()]
    for kw in EMERGENCY_KEYWORDS["English"]:
        if kw in tokens:
            return kw

    # Check Tamil keywords (direct substring match is safer because of word builders)
    for kw in EMERGENCY_KEYWORDS["Tamil"]:
        if kw in text:
            return kw

    return None


TRANSLATION_DICT = {
    "Tamil": {
        "HELLO": "வணக்கம்",
        "THANK YOU": "நன்றி",
        "PLEASE": "தயவுசெய்து",
        "YES": "ஆம்",
        "NO": "இல்லை",
        "GOODBYE": "போய் வருகிறேன்",
        "SORRY": "மன்னிக்கவும்",
        "HELP": "உதவி",
        "I LOVE YOU": "நான் உன்னை காதலிக்கிறேன்",
        "GOOD MORNING": "காலை வணக்கம்",
        "GOOD NIGHT": "இரவு வணக்கம்",
        "WELCOME": "வரவேற்கிறோம்",
        "HOW ARE YOU": "நீங்கள் எப்படி இருக்கிறீர்கள்",
        "FINE": "நலம்",
        "MY NAME IS": "என் பெயர்",
        "WHAT": "என்ன",
        "WHY": "ஏன்",
        "WHEN": "எப்போது",
        "WHERE": "எங்கே",
        "WHO": "யார்",
        "HOW": "எப்படி",
        "MY": "என்",
        "YOUR": "உங்கள்",
        "NAME": "பெயர்",
        "FATHER": "அப்பா",
        "MOTHER": "அம்மா",
        "BROTHER": "சகோதரர்",
        "SISTER": "சகோதரி",
        "FRIEND": "நண்பர்",
        "WATER": "தண்ணீர்",
        "FOOD": "உணவு",
        "HOUSE": "வீடு",
        "SCHOOL": "பள்ளி",
        "BOOK": "புத்தகம்",
        "PEN": "பேனா",
        "OK": "சரி",
        "STOP": "நிறுத்து",
        "GO": "செல்",
        "COME": "வா",
        "SIT": "உட்கார்",
        "STAND": "எழுந்திரு",
        "EAT": "சாப்பிடு",
        "DRINK": "குடி",
        "SLEEP": "தூங்கு",
        "LOVE": "அன்பு",
        "HAPPY": "மகிழ்ச்சி",
        "SAD": "சோகம்",
        "BIG": "பெரிய",
        "SMALL": "சிறிய",
        "HOT": "சூடான",
        "COLD": "குளிர்",
        "HI": "வணக்கம்"
    }
}


# ── Global Translator & Cache for Real-Time Translation ──────────────────────
_google_translator = None
_translation_cache = {}

def translate_to_tamil(text: str) -> str:
    """
    Translates English text to Tamil using googletrans==4.0.0rc1.
    Utilizes local dictionary mapping first, then memory cache, and finally 
    falls back to the googletrans API to prevent UI freezing and API limit issues.
    """
    global _google_translator
    if not text or not text.strip():
        return text

    cleaned_text = text.strip()
    upper_text = cleaned_text.upper()

    # 1. Try local dictionary lookup first (instant & offline-friendly)
    lang_dict = TRANSLATION_DICT.get("Tamil", {})
    if upper_text in lang_dict:
        return lang_dict[upper_text]

    # 2. Check memory cache for previous translations
    if cleaned_text in _translation_cache:
        return _translation_cache[cleaned_text]

    # 3. Call googletrans API
    try:
        if _google_translator is None:
            from googletrans import Translator
            _google_translator = Translator()
        
        result = _google_translator.translate(cleaned_text, src='en', dest='ta')
        if result and result.text:
            _translation_cache[cleaned_text] = result.text
            return result.text
    except Exception as e:
        print(f"[WARN] googletrans translation failed: {e}")

    # Cache original text on failure to prevent spamming the API on every frame
    _translation_cache[cleaned_text] = text
    return text


# ═══════════════════════════════════════════════════════════════════════════
# Translation Engine (modular design for multilingual support)
# ═══════════════════════════════════════════════════════════════════════════

class TranslationEngine:
    """
    Modular translation engine supporting English → target language.

    Currently uses googletrans-based translation for Tamil with local dictionary backup.
    Designed to seamlessly integrate API-based translation (Google Translate,
    DeepL, etc.) without refactoring the calling code.

    Usage:
        translator = TranslationEngine(target_lang="Tamil")
        text = translator.translate("HELLO")  # → "வணக்கம்"

    To add a new language:
        1. Add entry to LANGUAGE_CONFIG
        2. Add translations to TRANSLATION_DICT
        3. (Optional) Implement API-based fallback in _api_translate()
    """

    def __init__(self, target_lang="English"):
        self.target_lang = target_lang

    @property
    def is_active(self):
        return self.target_lang != "English"

    def translate(self, text: str) -> str:
        if not self.is_active or not text:
            return text

        if self.target_lang == "Tamil":
            return translate_to_tamil(text)

        lang_dict = TRANSLATION_DICT.get(self.target_lang, {})
        upper_text = text.upper().strip()

        # 1. Try full-phrase match
        if upper_text in lang_dict:
            return lang_dict[upper_text]

        # 2. Try word-by-word translation
        words = upper_text.split()
        translated_words = []
        for word in words:
            if word in lang_dict:
                translated_words.append(lang_dict[word])
            else:
                translated_words.append(word)

        result = " ".join(translated_words)

        # 3. If no dictionary match at all, try API (fallback)
        if result == upper_text and upper_text:
            result = self._api_translate(text)

        return result

    def _api_translate(self, text: str) -> str:
        """
        Translates text using Google Translate via deep-translator.
        Falls back to original text if offline or if an error occurs.
        """
        try:
            from deep_translator import GoogleTranslator
            target_code = LANGUAGE_CONFIG.get(self.target_lang, {}).get("code", "en")
            return GoogleTranslator(source='en', target=target_code).translate(text)
        except Exception as e:
            print(f"[WARN] Translation failed (offline or API error): {e}")
            return text



# ═══════════════════════════════════════════════════════════════════════════
# Speech Engine (persistent worker thread + queue architecture)
# ═══════════════════════════════════════════════════════════════════════════

import queue  # stdlib, for thread-safe speech request passing


class SpeechEngine:
    """
    Production-grade TTS wrapper using pyttsx3.

    Architecture:
      Main Thread -> speak(text) -> Queue.put(text)
      Worker Thread -> Queue.get() -> engine.say() -> engine.runAndWait()

    Features:
      - Engine is created once and kept alive for the lifetime of the application.
      - Supports non-blocking speech with simple thread-safe queue.
      - Prevents overlapping speech requests.
      - Logs diagnostic properties (Worker Alive, Queue Size, Current Status, is_speaking).
    """

    _instance = None
    _init_lock = threading.Lock()

    # Speech status constants
    STATUS_READY = "READY"
    STATUS_SPEAKING = "SPEAKING"
    STATUS_COMPLETED = "COMPLETED"

    def __new__(cls):
        """Singleton: ensure only one SpeechEngine instance exists."""
        with cls._init_lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        """Initialize the speech engine interface (runs only once)."""
        if self._initialized:
            return
        self._initialized = True

        # Thread-safe state tracking
        self._status_lock = threading.Lock()
        self._status = self.STATUS_READY
        self._is_speaking_val = False
        self._just_completed_flag = False
        self._current_text = ""
        self._completed_timestamp = 0.0
        self._completed_display_duration = 2.0  # Show COMPLETED for 2s
        self._auto_cleared = False  # One-shot flag for auto-clear

        # Queue and shutdown signal
        self._queue = queue.Queue()
        self._shutdown_event = threading.Event()

        # Engine-available flag for compatibility
        self._engine_ready = threading.Event()

        # Launch persistent worker thread
        self._worker_thread = threading.Thread(
            target=self._worker_loop,
            name="SpeechWorkerThread",
            daemon=True
        )
        self._worker_thread.start()

        print("[OK] TTS persistent speech engine initialized.")

    def _worker_loop(self):
        """Persistent background worker loop that handles pyttsx3 commands."""
        import pythoncom
        pythoncom.CoInitialize()
        engine = None
        try:
            print("[DEBUG] Engine Created (Single Instance)")
            engine = pyttsx3.init()
            engine.setProperty("rate", TTS_SPEECH_RATE)
            engine.setProperty("volume", TTS_VOLUME)
            self._engine_ready.set()
        except Exception as e:
            print(f"[ERROR] Failed to initialize pyttsx3 engine: {e}")
            pythoncom.CoUninitialize()
            return

        while not self._shutdown_event.is_set():
            try:
                # Non-blocking fetch with 100ms timeout
                request = self._queue.get(timeout=0.1)
            except queue.Empty:
                continue

            text, language, volume = request

            # Update state to SPEAKING
            with self._status_lock:
                self._is_speaking_val = True
                self._status = self.STATUS_SPEAKING
                self._current_text = text
                self._auto_cleared = False

            # Diagnostic logs after every request received
            worker_alive = self._worker_thread.is_alive()
            print(f"[DEBUG TTS] Worker Alive: {worker_alive} | Queue Size: {self._queue.qsize()} | Status: {self._status} | is_speaking: {self._is_speaking_val}")

            try:
                # Set dynamic volume override
                engine.setProperty("volume", volume if volume is not None else TTS_VOLUME)

                # Attempt Tamil voice selection if requested
                if language == "Tamil":
                    try:
                        voices = engine.getProperty("voices")
                        tamil_voice_found = False
                        for voice in voices:
                            voice_name = voice.name.lower() if hasattr(voice, 'name') else ""
                            voice_id = voice.id.lower() if hasattr(voice, 'id') else ""
                            if 'tamil' in voice_name or 'ta' in voice_id or 'ta-in' in voice_id:
                                engine.setProperty("voice", voice.id)
                                print("[TTS] Tamil voice selected.")
                                tamil_voice_found = True
                                break
                        if not tamil_voice_found:
                            print("[TTS] Tamil voice not found, using default voice.")
                    except Exception as ve:
                        print(f"[TTS] Tamil voice selection error: {ve}")
                else:
                    # Reset voice to default (usually English)
                    try:
                        voices = engine.getProperty("voices")
                        for voice in voices:
                            voice_name = voice.name.lower() if hasattr(voice, 'name') else ""
                            if 'tamil' not in voice_name:
                                engine.setProperty("voice", voice.id)
                                break
                    except Exception:
                        pass

                print("[DEBUG] Speech Started")
                engine.say(text)
                engine.runAndWait()
                print("[DEBUG] Speech Finished")

            except Exception as e:
                print(f"[ERROR] Exception during speech execution: {e}")
            finally:
                self._queue.task_done()

                # Reset speaking state to COMPLETED
                with self._status_lock:
                    self._is_speaking_val = False
                    self._status = self.STATUS_COMPLETED
                    self._completed_timestamp = time.time()
                    self._just_completed_flag = True
                print("[DEBUG] Status Reset")

                # Diagnostic logs after request processed
                worker_alive = self._worker_thread.is_alive()
                print(f"[DEBUG TTS] Worker Alive: {worker_alive} | Queue Size: {self._queue.qsize()} | Status: {self.status} | is_speaking: {self.is_speaking}")

        # Shutdown cleanup
        if engine is not None:
            try:
                engine.stop()
            except Exception:
                pass
            del engine
            print("[DEBUG] Engine Destroyed")

        pythoncom.CoUninitialize()

    # ── Public API (called from the main/UI thread) ─────────────────────

    @property
    def status(self) -> str:
        """Current speech status: READY, SPEAKING, or COMPLETED."""
        with self._status_lock:
            # Auto-transition COMPLETED → READY after the display duration
            if (self._status == self.STATUS_COMPLETED
                    and time.time() - self._completed_timestamp
                    > self._completed_display_duration):
                self._status = self.STATUS_READY
            return self._status

    @property
    def is_speaking(self) -> bool:
        """True if TTS is currently producing audio."""
        with self._status_lock:
            return self._is_speaking_val

    @property
    def just_completed(self) -> bool:
        """
        True ONCE after speech finishes, for triggering auto-clear.
        Calling this consumes the flag (one-shot).
        """
        with self._status_lock:
            if self._just_completed_flag:
                self._just_completed_flag = False
                return True
            return False

    def speak(self, text: str, language: str = "English", volume: float = None) -> bool:
        """
        Queue a speech request to be processed by the background worker thread.

        Args:
            text: The text to speak.
            language: Language for TTS voice selection ("English" or "Tamil").
            volume: Volume level override (0.0 to 1.0).

        Returns True if the request was accepted (queued), False if rejected (empty text).
        """
        print("[DEBUG] speak() called")
        if not text or not text.strip():
            print("[TTS] No text to speak.")
            return False

        clean_text = text.strip()

        # Push to the thread-safe queue
        self._queue.put((clean_text, language, volume))
        print("[DEBUG] Queue Accepted")
        
        # Diagnostic logs on the main thread after queuing
        worker_alive = self._worker_thread.is_alive()
        print(f"[DEBUG TTS] Queue Size: {self._queue.qsize()} | Worker Alive: {worker_alive} | Status: {self.status} | is_speaking: {self.is_speaking}")
        return True

    def shutdown(self):
        """Set shutdown signal to clean up thread on exit."""
        self._shutdown_event.set()
        if self._worker_thread.is_alive():
            self._worker_thread.join(timeout=1.0)



def save_recognition(recognized_text: str, translated_text: str = "",
                     selected_language: str = "English", confidence: float = 100.0) -> bool:
    """
    Saves the recognized text, translation, language, confidence, and timestamp to Supabase.
    """
    try:
        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).isoformat()
        
        sb = SupabaseManager()
        
        data = {
            "recognized_text": recognized_text,
            "translated_text": translated_text,
            "selected_language": selected_language,
            "confidence": confidence,
            "created_at": timestamp
        }
        
        res = sb.insert("recognition_history", data)
        if res is not None:
            print("[DB] Saved Successfully")
            return True
        else:
            print("[DB] Save Failed")
            return False
            
    except Exception as e:
        print("[DB] Save Failed")
        print(f"     Error: {e}")
        return False


def get_recent_history() -> list | None:
    """
    Fetches the latest 20 records from recognition_history table.
    """
    try:
        sb = SupabaseManager()
        res = sb.client.table("recognition_history").select("*").order("created_at", descending=True).limit(20).execute()
        return res.data
    except Exception as e:
        print(f"[DB] Error fetching history: {e}")
        return None


# ── Emergency Assistance Mode Modules ────────────────────────────────────────

def _play_emergency_sound():
    """Plays a non-blocking siren tone using Windows winsound."""
    import winsound
    try:
        # Playing a high-low siren tone
        for _ in range(3):
            winsound.Beep(1200, 250)
            winsound.Beep(800, 250)
    except Exception as e:
        print(f"[WARN] Emergency audio alert failed: {e}")


def trigger_sound_alert():
    """Trigger the emergency sound alert in a separate background thread."""
    threading.Thread(target=_play_emergency_sound, name="EmergencySoundThread", daemon=True).start()


def save_emergency_event(detected_keyword: str, recognized_text: str,
                         translated_text: str = "", language: str = "English",
                         confidence: float = 100.0) -> bool:
    """
    Saves the emergency event details to the Supabase table `emergency_events`.
    """
    try:
        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).isoformat()
        
        sb = SupabaseManager()
        
        data = {
            "detected_keyword": detected_keyword,
            "recognized_text": recognized_text,
            "translated_text": translated_text,
            "language": language,
            "confidence": confidence,
            "created_at": timestamp
        }
        
        res = sb.insert("emergency_events", data)
        if res is not None:
            print("[DB] Emergency Event Saved Successfully")
            return True
        else:
            print("[DB] Save Emergency Event Failed")
            return False
    except Exception as e:
        print("[DB] Save Emergency Event Failed")
        print(f"     Error: {e}")
        return False


def get_emergency_history() -> list | None:
    """
    Fetches the latest 5 records from emergency_events table in Supabase.
    """
    try:
        sb = SupabaseManager()
        res = sb.client.table("emergency_events").select("*").order("created_at", descending=True).limit(5).execute()
        return res.data
    except Exception as e:
        print(f"[DB] Error fetching emergency history: {e}")
        return None


def print_emergency_history():
    """Fetches and prints the recent emergency events history to the console."""
    history = get_emergency_history()
    if history:
        print("\n" + "═" * 58)
        print("  EMERGENCY ASSISTANCE LOGS (Latest 5 Events)")
        print("═" * 58)
        for event in history:
            kw = event.get("detected_keyword", "N/A")
            msg = event.get("recognized_text", "N/A")
            created_at = event.get("created_at", "N/A")
            lang = event.get("language", "English")
            
            try:
                from datetime import datetime
                time_part = datetime.fromisoformat(created_at.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M:%S")
            except Exception:
                time_part = created_at
                
            print(f"[{time_part}] | Language: {lang} | Keyword: {kw}")
            print(f"  Recognized Text: {msg}")
            print("-" * 58)
        print("═" * 58 + "\n")


def get_emergency_count_today() -> int:
    """
    Queries Supabase to get the number of emergency events created today (UTC).
    """
    try:
        from datetime import datetime, timezone
        now_utc = datetime.now(timezone.utc)
        today_start = datetime(now_utc.year, now_utc.month, now_utc.day, tzinfo=timezone.utc).isoformat()
        
        sb = SupabaseManager()
        res = sb.client.table("emergency_events").select("id", count="exact").gte("created_at", today_start).execute()
        return res.count if res.count is not None else len(res.data)
    except Exception as e:
        print(f"[DB] Error getting today's emergency count: {e}")
        return 0


# ── Future-Ready Notification Hooks (Optional Modules) ────────────────────────

def send_sms_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: SMS Integration (e.g., Twilio)."""
    pass


def send_whatsapp_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: WhatsApp Business API integration."""
    pass


def send_email_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: Email Notification (SMTP / SendGrid)."""
    pass


def notify_caregiver(keyword: str, recognized_text: str, language: str):
    """Optional future module: Push Notifications to Caregiver companion app."""
    pass


def share_location():
    """Optional future module: Location Sharing (GPS / IP Geolocation)."""
    return "Lat: 13.0827, Lon: 80.2707 (Chennai, India)"


# ═══════════════════════════════════════════════════════════════════════════
# Model & Feature Extraction
# ═══════════════════════════════════════════════════════════════════════════

def load_model():
    """Load the trained MLP model, label encoder, and scaler."""
    global MODEL_EXPECTS_ENHANCED
    for path in (MODEL_PATH, ENCODER_PATH, SCALER_PATH):
        if not os.path.exists(path):
            print(f"[ERROR] Missing file: {path}")
            print("        Run train_mlp.py first to generate model artefacts.")
            sys.exit(1)

    model = joblib.load(MODEL_PATH)
    le = joblib.load(ENCODER_PATH)
    scaler = joblib.load(SCALER_PATH)

    # Determine model input dimension dynamically
    if hasattr(scaler, 'n_features_in_'):
        num_feats = scaler.n_features_in_
    elif hasattr(model, 'n_features_in_'):
        num_feats = model.n_features_in_
    else:
        num_feats = 63  # default fallback

    MODEL_EXPECTS_ENHANCED = (num_feats == 99)
    print(f"[OK] Model, encoder, and scaler loaded. Expected features: {num_feats}")
    if not MODEL_EXPECTS_ENHANCED:
        print("[WARN] Compatibility Mode Active: Loaded model expects 63 features (raw landmarks).")
        print("       Please run train_mlp.py to retrain the model with 99 enhanced features for maximum stability.")
    else:
        print("[OK] Enhanced Feature Mode Active: Using 99 normalized & engineered features.")

    return model, le, scaler


def extract_landmarks(hand_landmarks) -> np.ndarray:
    """Convert MediaPipe hand landmarks to a flat 63-element array."""
    coords = []
    for lm in hand_landmarks.landmark:
        coords.extend([lm.x, lm.y, lm.z])
    return np.array(coords, dtype=np.float32).reshape(1, -1)


# ═══════════════════════════════════════════════════════════════════════════
# HUD Drawing Utilities
# ═══════════════════════════════════════════════════════════════════════════

def draw_unicode_text(frame, text, position, color, font_size=24, thickness=1):
    """Render Unicode text (Tamil, etc.) on an OpenCV frame using PIL by cropping the local area for performance."""
    if not PIL_AVAILABLE or not text:
        cv2.putText(frame, text, position, cv2.FONT_HERSHEY_SIMPLEX,
                    font_size / 30, (180, 180, 180), thickness, cv2.LINE_AA)
        return

    try:
        h, w = frame.shape[:2]
        x, y = position
        
        # Estimate text dimensions (generous padding)
        text_h = int(font_size * 1.6)
        text_w = int(len(text) * font_size * 1.2)
        
        # Define bounding box for cropping (constrain within frame boundaries)
        x1 = max(0, x - 10)
        y1 = max(0, y - 5)
        x2 = min(w, x + text_w + 10)
        y2 = min(h, y + text_h + 5)
        
        if x2 <= x1 or y2 <= y1:
            return
            
        # Crop only the local region of interest
        roi = frame[y1:y2, x1:x2]
        
        # Render text on ROI using PIL
        pil_img = Image.fromarray(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
        draw = ImageDraw.Draw(pil_img)
        
        font = None
        for font_path in [
            "C:/Windows/Fonts/Nirmala.ttf",
            "C:/Windows/Fonts/Latha.ttf",
            "C:/Windows/Fonts/Arial.ttf",
        ]:
            try:
                font = ImageFont.truetype(font_path, font_size)
                break
            except Exception:
                continue
        if font is None:
            font = ImageFont.load_default()
            
        # Local text position is relative to ROI origin
        local_pos = (x - x1, y - y1)
        draw.text(local_pos, text, font=font, fill=color)
        
        # Convert back and paste onto frame
        frame[y1:y2, x1:x2] = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
    except Exception as e:
        cv2.putText(frame, text, position, cv2.FONT_HERSHEY_SIMPLEX,
                    font_size / 30, (180, 180, 180), thickness, cv2.LINE_AA)


def check_hand_quality(hand_landmarks):
    """
    Checks if the hand landmarks meet quality criteria (Phase 7):
      - Not too close to the edge (within 2% margin)
      - Not too small (bounding box width and height >= 12% of screen)
    """
    xs = [lm.x for lm in hand_landmarks.landmark]
    ys = [lm.y for lm in hand_landmarks.landmark]
    
    # 1. Edge check
    edge_margin = 0.02
    for x, y in zip(xs, ys):
        if x < edge_margin or x > (1.0 - edge_margin) or y < edge_margin or y > (1.0 - edge_margin):
            return False, "Hand Too Close to Edge"
            
    # 2. Size check
    bbox_w = max(xs) - min(xs)
    bbox_h = max(ys) - min(ys)
    min_size = 0.12
    if bbox_w < min_size or bbox_h < min_size:
        return False, "Hand Too Small / Far"
        
    return True, "OK"


def calculate_hand_movement(current_landmarks, prev_landmarks_pts) -> float:
    """
    Calculates average 2D landmark displacement between consecutive frames (Phase 6).
    prev_landmarks_pts is a list/ndarray of shape (21, 2).
    """
    if current_landmarks is None or prev_landmarks_pts is None:
        return 0.0
    curr_pts = np.array([[lm.x, lm.y] for lm in current_landmarks.landmark], dtype=np.float32)
    prev_pts = np.array(prev_landmarks_pts, dtype=np.float32)
    if curr_pts.shape != prev_pts.shape:
        return 0.0
    distances = np.linalg.norm(curr_pts - prev_pts, axis=1)
    return float(np.mean(distances))


def draw_rounded_rect(img, pt1, pt2, color, radius=18, thickness=-1, alpha=0.7):
    """Draw a filled rounded rectangle with transparency."""
    overlay = img.copy()
    x1, y1 = pt1
    x2, y2 = pt2

    # Draw rectangle body
    cv2.rectangle(overlay, (x1 + radius, y1), (x2 - radius, y2), color, thickness)
    cv2.rectangle(overlay, (x1, y1 + radius), (x2, y2 - radius), color, thickness)

    # Draw corners
    cv2.ellipse(overlay, (x1 + radius, y1 + radius), (radius, radius), 180, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x2 - radius, y1 + radius), (radius, radius), 270, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x1 + radius, y2 - radius), (radius, radius), 90, 0, 90, color, thickness)
    cv2.ellipse(overlay, (x2 - radius, y2 - radius), (radius, radius), 0, 0, 90, color, thickness)

    cv2.addWeighted(overlay, alpha, img, 1 - alpha, 0, img)


def draw_confidence_bar(img, x, y, w, h, confidence, color):
    """Draw a sleek confidence bar."""
    # Background bar
    cv2.rectangle(img, (x, y), (x + w, y + h), (50, 50, 60), -1)
    cv2.rectangle(img, (x, y), (x + w, y + h), (80, 80, 90), 1)
    # Filled portion
    fill_w = int(w * confidence)
    if fill_w > 0:
        cv2.rectangle(img, (x + 1, y + 1), (x + fill_w - 1, y + h - 1), color, -1)


def draw_hold_progress_bar(img, x, y, w, h, progress, color):
    """Draw an animated hold-time progress bar with a glow effect."""
    # Background track
    cv2.rectangle(img, (x, y), (x + w, y + h), (40, 40, 50), -1)
    cv2.rectangle(img, (x, y), (x + w, y + h), (70, 70, 80), 1)

    fill_w = int(w * min(progress, 1.0))
    if fill_w > 0:
        # Main fill
        cv2.rectangle(img, (x + 1, y + 1), (x + fill_w - 1, y + h - 1), color, -1)
        # Bright leading edge (glow)
        edge_x = x + fill_w - 1
        if edge_x > x + 2:
            cv2.line(img, (edge_x, y + 1), (edge_x, y + h - 1), WHITE, 1)


def draw_hud(frame, prediction, confidence, probabilities, label_names,
             word_buffer, sentence_buffer, fps, hand_detected, state,
             speech_status, selected_language="English", translated_text=""):
    """
    Draw a polished heads-up display overlay.

    The `state` dict provides temporal-logic feedback:
      - stable_prediction: the majority-voted prediction (or None)
      - hold_elapsed: seconds held so far (0.0 if not holding)
      - is_holding: True if currently counting down the hold timer
      - locked_until_reset: True if waiting for hand-reset
      - feedback_message: e.g. "Added A" (or None)

    Args:
        selected_language: Current language mode ("English" or "Tamil").
        translated_text: Tamil translation of the sentence buffer (Tamil mode only).
    """
    h, w = frame.shape[:2]

    # ── Top-left: Title bar ─────────────────────────────────────────────────
    draw_rounded_rect(frame, (10, 10), (560, 55), BG_DARK, radius=12, alpha=0.85)
    cv2.putText(frame, "ASL Sign Language", (24, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, TEAL, 2, cv2.LINE_AA)

    # Language indicator
    lang_color = TEAL if selected_language == "English" else ORANGE
    cv2.putText(frame, f"Language: {selected_language}", (220, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.48, lang_color, 1, cv2.LINE_AA)

    cv2.putText(frame, f"FPS: {fps:.0f}", (390, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, GRAY, 1, cv2.LINE_AA)

    # Speech status indicator (top bar, right of FPS)
    if speech_status == SpeechEngine.STATUS_SPEAKING:
        status_color = ORANGE
        status_icon = ">> SPEAKING"
    elif speech_status == SpeechEngine.STATUS_COMPLETED:
        status_color = GREEN
        status_icon = "DONE"
    else:
        status_color = GRAY
        status_icon = "TTS READY"
    cv2.putText(frame, status_icon, (400, 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38, status_color, 1, cv2.LINE_AA)

    # ── Main prediction panel (right side) ──────────────────────────────────
    panel_x = w - 280
    panel_y = 10
    panel_w = 270
    panel_h = 360
    draw_rounded_rect(frame, (panel_x, panel_y),
                      (panel_x + panel_w, panel_y + panel_h),
                      BG_DARK, radius=14, alpha=0.85)

    if hand_detected:
        status = state.get("hand_status", "OK")
        if status != "OK":
            # Display Status (e.g., "Hand Not Ready" or "Hand Moving")
            status_color = YELLOW if status == "Hand Moving" else RED
            status_size = cv2.getTextSize(status, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)[0]
            status_x = panel_x + (panel_w - status_size[0]) // 2
            cv2.putText(frame, status, (status_x, panel_y + 100),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, status_color, 2, cv2.LINE_AA)

            detail = state.get("hand_status_detail", "")
            if detail:
                detail_size = cv2.getTextSize(detail, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)[0]
                detail_x = panel_x + (panel_w - detail_size[0]) // 2
                cv2.putText(frame, detail, (detail_x, panel_y + 135),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.45, GRAY, 1, cv2.LINE_AA)
        elif prediction:
            # Determine prediction display (Unknown if confidence < CONFIDENCE_THRESHOLD)
            is_confident = (confidence >= CONFIDENCE_THRESHOLD)
            display_pred = prediction if is_confident else "Unknown"
            
            # Prediction letter — large
            pred_color = TEAL if is_confident else RED
            letter_size = cv2.getTextSize(display_pred, cv2.FONT_HERSHEY_SIMPLEX, 2.2 if not is_confident else 3.0, 4)[0]
            letter_x = panel_x + (panel_w - letter_size[0]) // 2
            cv2.putText(frame, display_pred, (letter_x, panel_y + 80),
                        cv2.FONT_HERSHEY_SIMPLEX, 2.2 if not is_confident else 3.0, pred_color, 3 if not is_confident else 4, cv2.LINE_AA)

            # Confidence percentage
            conf_text = f"{confidence * 100:.1f}%"
            conf_color = GREEN if is_confident else RED
            conf_size = cv2.getTextSize(conf_text, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)[0]
            conf_x = panel_x + (panel_w - conf_size[0]) // 2
            cv2.putText(frame, conf_text, (conf_x, panel_y + 110),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, conf_color, 2, cv2.LINE_AA)

            # Confidence bar
            draw_confidence_bar(frame, panel_x + 20, panel_y + 120,
                                panel_w - 40, 14, confidence, conf_color)

            # ── Hold-time progress (temporal feedback) ──────────────────────────
            y_hold = panel_y + 150
            if state["is_holding"]:
                elapsed = state["hold_elapsed"]
                progress = elapsed / HOLD_TIME_REQUIRED
                hold_text = f"Hold: {elapsed:.1f} / {HOLD_TIME_REQUIRED:.1f}s"
                bar_color = GREEN if progress > 0.8 else ORANGE
                cv2.putText(frame, hold_text, (panel_x + 15, y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.48, YELLOW, 1, cv2.LINE_AA)
                draw_hold_progress_bar(frame, panel_x + 20, y_hold + 6,
                                       panel_w - 40, 12, progress, bar_color)
                y_hold += 32
            elif state["locked_until_reset"]:
                cv2.putText(frame, "Locked (change sign/remove hand)",
                            (panel_x + 12, y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.35, GRAY, 1, cv2.LINE_AA)
                y_hold += 22
            elif not is_confident:
                cv2.putText(frame, f"Low confidence (<{CONFIDENCE_THRESHOLD*100:.0f}%)",
                            (panel_x + 12, y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.38, RED, 1, cv2.LINE_AA)
                y_hold += 22
            else:
                y_hold += 5  # small gap

            # ── Top-3 predictions ───────────────────────────────────────────────
            top_indices = np.argsort(probabilities)[::-1][:3]
            y_offset = y_hold + 10
            cv2.putText(frame, "Top Predictions:", (panel_x + 15, y_offset),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, GRAY, 1, cv2.LINE_AA)
            y_offset += 28
            for rank, idx in enumerate(top_indices, 1):
                lbl = label_names[idx]
                prob = probabilities[idx]
                bar_color = TEAL if rank == 1 else TEAL_LIGHT
                text = f"{rank}. {lbl}"
                cv2.putText(frame, text, (panel_x + 15, y_offset),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, WHITE, 1, cv2.LINE_AA)
                draw_confidence_bar(frame, panel_x + 60, y_offset - 10,
                                    panel_w - 90, 10, prob, bar_color)
                pct = f"{prob * 100:.1f}%"
                cv2.putText(frame, pct, (panel_x + panel_w - 55, y_offset),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.38, GRAY, 1, cv2.LINE_AA)
                y_offset += 28
    else:
        # No hand detected
        msg = "No Hand Detected"
        msg_size = cv2.getTextSize(msg, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)[0]
        msg_x = panel_x + (panel_w - msg_size[0]) // 2
        cv2.putText(frame, msg, (msg_x, panel_y + 100),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, GRAY, 2, cv2.LINE_AA)

        hint = "Show your hand"
        hint_size = cv2.getTextSize(hint, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)[0]
        hint_x = panel_x + (panel_w - hint_size[0]) // 2
        cv2.putText(frame, hint, (hint_x, panel_y + 135),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, GRAY, 1, cv2.LINE_AA)

    # ── Emergency events daily counter (always visible at bottom of right panel) ──
    emergency_count = state.get("emergency_count_today", 0)
    counter_text = f"Emergency Events Today: {emergency_count}"
    cv2.putText(frame, counter_text, (panel_x + 15, panel_y + panel_h - 15),
                cv2.FONT_HERSHEY_SIMPLEX, 0.42, (80, 80, 255) if emergency_count > 0 else GRAY, 1, cv2.LINE_AA)

    # ── Feedback banner (e.g. "Added A") ────────────────────────────────────
    if state["feedback_message"]:
        fb_text = state["feedback_message"]
        fb_size = cv2.getTextSize(fb_text, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2)[0]
        fb_x = (w - fb_size[0]) // 2
        fb_y = h // 2 - 40
        draw_rounded_rect(frame, (fb_x - 20, fb_y - 35),
                          (fb_x + fb_size[0] + 20, fb_y + 15),
                          (20, 100, 20), radius=14, alpha=0.85)
        cv2.putText(frame, fb_text, (fb_x, fb_y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, GREEN, 2, cv2.LINE_AA)

    # ── Tamil translation bar (only visible in Tamil mode) ──────────────────
    if selected_language == "Tamil" and translated_text:
        tamil_bar_h = 38
        tamil_bar_y = h - 55 - 10 - 45 - 8 - tamil_bar_h - 4
        draw_rounded_rect(frame, (10, tamil_bar_y), (w - 10, tamil_bar_y + tamil_bar_h),
                          BG_DARK, radius=12, alpha=0.80)
        cv2.putText(frame, "Tamil:", (24, tamil_bar_y + 26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.48, ORANGE, 1, cv2.LINE_AA)
        draw_unicode_text(frame, translated_text,
                          (90, tamil_bar_y + 4), (ORANGE), font_size=26, thickness=1)

    # ── Sentence buffer (second-from-bottom bar) ────────────────────────────
    sent_bar_h = 45
    sent_bar_y = h - 55 - 10 - sent_bar_h - 8
    draw_rounded_rect(frame, (10, sent_bar_y), (w - 10, sent_bar_y + sent_bar_h),
                      BG_DARK, radius=12, alpha=0.80)

    # Label changes to "English:" in Tamil mode
    sent_label = "English:" if selected_language == "Tamil" else "Sentence:"
    cv2.putText(frame, sent_label, (24, sent_bar_y + 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.48, PURPLE, 1, cv2.LINE_AA)

    sentence_text = " ".join(sentence_buffer) if sentence_buffer else "(press SPACE to finish words)"
    sent_color = WHITE if sentence_buffer else GRAY
    # Position text slightly to the left if using shorter "English:" label
    text_x_pos = 100 if selected_language == "Tamil" else 120
    cv2.putText(frame, sentence_text, (text_x_pos, sent_bar_y + 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, sent_color, 1, cv2.LINE_AA)

    # ── Word buffer (bottom bar) ────────────────────────────────────────────
    bar_h = 55
    bar_y = h - bar_h - 10
    draw_rounded_rect(frame, (10, bar_y), (w - 10, bar_y + bar_h),
                      BG_DARK, radius=12, alpha=0.85)

    cv2.putText(frame, "Word:", (24, bar_y + 35),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, GRAY, 1, cv2.LINE_AA)

    word_text = "".join(word_buffer) if word_buffer else "_"
    cv2.putText(frame, word_text, (90, bar_y + 36),
                cv2.FONT_HERSHEY_SIMPLEX, 0.75, WHITE, 2, cv2.LINE_AA)

    # Controls hint
    controls = "[Q]Quit [C]Clear [L]Lang [SPC]Word [BKSP]Del [ENTER]Speak"
    cv2.putText(frame, controls, (w - 480, bar_y + 36),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38, GRAY, 1, cv2.LINE_AA)

    # ── Emergency Pop-up Modal (drawn on top of all elements) ──────────────────
    if state.get("emergency_active", False):
        emergency_keyword = state.get("emergency_keyword", "UNKNOWN")
        emergency_time = state.get("emergency_trigger_time", time.time())
        emergency_language = state.get("emergency_language", "English")
        
        alert_w = 480
        alert_h = 200
        x1 = (w - alert_w) // 2
        y1 = (h - alert_h) // 2
        x2 = x1 + alert_w
        y2 = y1 + alert_h
        
        # Red background panel
        draw_rounded_rect(frame, (x1, y1), (x2, y2), (50, 50, 255), radius=16, alpha=0.95)
        # Border outline
        cv2.rectangle(frame, (x1, y1), (x2, y2), WHITE, 2, cv2.LINE_AA)
        
        # Indicator Circle (to simulate 🔴)
        cv2.circle(frame, (x1 + 35, y1 + 40), 10, (0, 0, 255), -1)
        cv2.circle(frame, (x1 + 35, y1 + 40), 12, WHITE, 1, cv2.LINE_AA)
        
        # Title text
        cv2.putText(frame, "EMERGENCY DETECTED", (x1 + 60, y1 + 47),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.75, WHITE, 2, cv2.LINE_AA)
        
        # Details
        cv2.putText(frame, f"Detected Keyword: {emergency_keyword}", (x1 + 30, y1 + 95),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, YELLOW, 2, cv2.LINE_AA)
        
        local_time_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(emergency_time))
        cv2.putText(frame, f"Timestamp: {local_time_str}", (x1 + 30, y1 + 135),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52, WHITE, 1, cv2.LINE_AA)
        
        cv2.putText(frame, f"Language: {emergency_language}", (x1 + 30, y1 + 170),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52, WHITE, 1, cv2.LINE_AA)


# ── Temporal Logic Engine ───────────────────────────────────────────────────

def get_majority_prediction(history, consistency_threshold):
    """
    Analyse the prediction history using majority voting.

    Returns (letter, ratio) if the most common prediction exceeds the
    consistency threshold, otherwise (None, 0.0).
    """
    if len(history) < history.maxlen:
        # Not enough history accumulated yet
        return None, 0.0

    counter = Counter(history)
    most_common_letter, count = counter.most_common(1)[0]
    ratio = count / len(history)

    if ratio >= consistency_threshold:
        return most_common_letter, ratio
    return None, ratio


# ═══════════════════════════════════════════════════════════════════════════
# Main Application Loop
# ═══════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "=" * 58)
    print("  ASL Sign Language - Live Prediction + Text-to-Speech")
    print("  Bilingual: English / Tamil  [Press L to toggle]")
    print("=" * 58)

    # ── Load model ──────────────────────────────────────────────────────────
    model, le, scaler = load_model()
    label_names = le.classes_

    # ── Initialize TTS engine (singleton) ───────────────────────────────────
    tts = SpeechEngine()

    # ── Initialize Supabase ─────────────────────────────────────────────────
    supabase = SupabaseManager()
    supabase.connect()

    # ── Initialize translation engine (bilingual support) ────────────────────
    translator = TranslationEngine(target_lang="English")

    # ── MediaPipe Hands ─────────────────────────────────────────────────────
    mp_hands = mp.solutions.hands
    mp_draw = mp.solutions.drawing_utils
    mp_styles = mp.solutions.drawing_styles

    hands = mp_hands.Hands(
        static_image_mode=False,
        max_num_hands=1,
        min_detection_confidence=0.7,
        min_tracking_confidence=0.5,
    )

    # ── Webcam ──────────────────────────────────────────────────────────────
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("[ERROR] Cannot open webcam.")
        sys.exit(1)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    print("[OK] Webcam opened. Press Q or ESC to quit.\n")

    # ── Language State ──────────────────────────────────────────────────────
    selected_language = "English"  # Default: "English" or "Tamil"

    # ── State Variables (Temporal Logic) ────────────────────────────────────
    word_buffer = deque(maxlen=50)       # Current word being built letter-by-letter
    word_confidences = []                # Confidence values for characters in the current word
    sentence_buffer = []                 # Accumulated words (list of strings)
    sentence_confidences = []            # Confidence values for characters in the sentence

    # Per-frame prediction output
    current_prediction = None            # Raw prediction from model this frame
    confidence = 0.0                     # Raw confidence from model this frame
    probabilities = np.zeros(len(label_names))

    # Prediction history for majority voting (last 20 frames)
    prediction_history = deque(maxlen=HISTORY_SIZE)

    # Hold timer: tracks when a stable prediction first appeared
    hold_timer_start = None              # time.time() when hold began, None if not holding

    # Lock state: prevents re-adding the same letter
    last_added_letter = None             # The last letter successfully committed
    locked_until_reset = False           # True = waiting for hand removal or new sign

    # Feedback overlay
    feedback_message = None              # e.g. "Added A"
    feedback_timestamp = 0.0             # time.time() when feedback was set

    # ── Emergency State Variables ───────────────────────────────────────────
    emergency_active = False
    emergency_keyword = ""
    emergency_trigger_time = 0.0
    emergency_language = "English"
    last_emergency_trigger_time = 0.0
    emergency_cooldown_duration = 30.0  # 30 seconds duplicate protection
    emergency_display_duration = 5.0    # Show alert popup for at least 5 seconds
    
    # Query today's emergency count on boot (cached value incremented locally)
    print("[DB] Fetching today's emergency events count...")
    emergency_count_today = get_emergency_count_today()
    print(f"[DB] Initialized today's count: {emergency_count_today}")

    # FPS tracking
    prev_time = time.time()
    fps = 0.0

    # Hand motion tracking
    prev_landmarks_pts = None

    print("[STATE] Temporal logic engine active:")
    print(f"        History window:   {HISTORY_SIZE} frames")
    print(f"        Consistency:      >{CONSISTENCY_THRESHOLD*100:.0f}%")
    print(f"        Confidence:       >={CONFIDENCE_THRESHOLD*100:.0f}%")
    print(f"        Hold time:        {HOLD_TIME_REQUIRED}s")
    print(f"        Auto-clear:       {AUTO_CLEAR}\n")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("[WARN] Failed to read frame, retrying...")
            continue

        frame = cv2.flip(frame, 1)  # mirror for natural interaction
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = hands.process(rgb)

        hand_detected = False
        now = time.time()

        # ── Expire feedback message after FEEDBACK_DISPLAY_DURATION ──────
        if feedback_message and (now - feedback_timestamp) > FEEDBACK_DISPLAY_DURATION:
            feedback_message = None

        # ── Expire emergency alert after emergency_display_duration ──────
        if emergency_active and (now - emergency_trigger_time) > emergency_display_duration:
            emergency_active = False

        # ── Auto-clear sentence buffer after speech completes ────────────
        # Uses the one-shot `just_completed` flag to fire exactly once,
        # preventing repeated clears every frame during the COMPLETED window.
        if AUTO_CLEAR and tts.just_completed and sentence_buffer:
            sentence_buffer.clear()
            sentence_confidences.clear()
            print("[AUTO-CLEAR] Sentence buffer cleared after speech.")

        # ================================================================
        # HAND DETECTED → run prediction + temporal logic
        # ================================================================
        hand_status = "No Hand Detected"
        hand_status_detail = ""

        if results.multi_hand_landmarks:
            hand_detected = True
            hand_lm = results.multi_hand_landmarks[0]

            # Draw hand landmarks with styled connections
            mp_draw.draw_landmarks(
                frame, hand_lm, mp_hands.HAND_CONNECTIONS,
                mp_styles.get_default_hand_landmarks_style(),
                mp_styles.get_default_hand_connections_style(),
            )

            # ── Step 1: Hand Quality Check (Phase 7) ─────────────────────
            quality_ok, quality_msg = check_hand_quality(hand_lm)
            
            # ── Step 2: Motion Check (Phase 6) ───────────────────────────
            is_moving = False
            movement_val = 0.0
            if prev_landmarks_pts is not None:
                movement_val = calculate_hand_movement(hand_lm, prev_landmarks_pts)
                if movement_val > 0.015:
                    is_moving = True
            # Store current landmarks for next frame motion check
            prev_landmarks_pts = [[lm.x, lm.y] for lm in hand_lm.landmark]

            if not quality_ok:
                hand_status = "Hand Not Ready"
                hand_status_detail = quality_msg
                current_prediction = None
                confidence = 0.0
                prediction_history.clear()
                hold_timer_start = None
            elif is_moving:
                hand_status = "Hand Moving"
                hand_status_detail = f"Speed: {movement_val:.3f}"
                current_prediction = None
                confidence = 0.0
                # Pause the hold timer while hand is moving rapidly
                hold_timer_start = None
            else:
                hand_status = "OK"
                hand_status_detail = ""

                # Extract features based on model expectation (Compatibility Mode)
                if MODEL_EXPECTS_ENHANCED:
                    features = extract_enhanced_features(hand_lm).reshape(1, -1)
                else:
                    features = extract_landmarks(hand_lm).reshape(1, -1)

                features_scaled = scaler.transform(features)
                current_prediction = le.inverse_transform(model.predict(features_scaled))[0]
                probabilities = model.predict_proba(features_scaled)[0]
                confidence = float(np.max(probabilities))

                # ── Step 3: Confidence Filtering (Phase 3) ───────────────────
                # Only accept predictions with >= 95% confidence
                filtered_pred = current_prediction if confidence >= CONFIDENCE_THRESHOLD else "Unknown"

                # ── Step 4: Append to prediction history ─────────────────────
                prediction_history.append(filtered_pred)

                # ── Step 5: Majority voting (Phases 4 & 5) ───────────────────
                stable_prediction, consistency_ratio = get_majority_prediction(
                    prediction_history, CONSISTENCY_THRESHOLD
                )

                # ── Step 6: Temporal decision logic ──────────────────────────
                if stable_prediction is not None and stable_prediction != "Unknown":
                    # We have a consistent, high-confidence prediction

                    # Check if locked: same letter was just added
                    if locked_until_reset and stable_prediction == last_added_letter:
                        # LOCKED: user must remove hand or change sign
                        hold_timer_start = None  # don't accumulate hold time

                    elif stable_prediction != last_added_letter:
                        # NEW LETTER detected (different from the locked one)
                        # This automatically unlocks the system
                        locked_until_reset = False

                        if hold_timer_start is None:
                            # Start the hold timer for this new stable prediction
                            hold_timer_start = now
                        else:
                            # Check if held long enough
                            hold_elapsed = now - hold_timer_start
                            if hold_elapsed >= HOLD_TIME_REQUIRED:
                                # ── COMMIT THE LETTER ───────────────────────
                                word_buffer.append(stable_prediction)
                                word_confidences.append(confidence)
                                last_added_letter = stable_prediction
                                locked_until_reset = True
                                hold_timer_start = None

                                # Set feedback
                                feedback_message = f"Added: {stable_prediction}"
                                feedback_timestamp = now

                                print(f"[COMMIT] '{stable_prediction}' added. "
                                      f"Word: {''.join(word_buffer)}")

                    else:
                        # Same letter, but not locked (first occurrence)
                        if hold_timer_start is None:
                            hold_timer_start = now
                        else:
                            hold_elapsed = now - hold_timer_start
                            if hold_elapsed >= HOLD_TIME_REQUIRED:
                                # ── COMMIT THE LETTER ───────────────────────
                                word_buffer.append(stable_prediction)
                                word_confidences.append(confidence)
                                last_added_letter = stable_prediction
                                locked_until_reset = True
                                hold_timer_start = None

                                feedback_message = f"Added: {stable_prediction}"
                                feedback_timestamp = now

                                print(f"[COMMIT] '{stable_prediction}' added. "
                                      f"Word: {''.join(word_buffer)}")
                else:
                    # Prediction is unstable, unknown, or low-confidence: reset hold timer
                    hold_timer_start = None

        # ================================================================
        # NO HAND DETECTED → reset all temporal state
        # ================================================================
        else:
            hand_status = "No Hand Detected"
            hand_status_detail = ""
            current_prediction = None
            confidence = 0.0
            prediction_history.clear()
            hold_timer_start = None
            prev_landmarks_pts = None

            # Hand removal resets the lock, allowing the same letter next time
            if locked_until_reset:
                locked_until_reset = False
                last_added_letter = None
                print("[RESET] Hand removed — lock cleared.")

        # ── Monitor Emergency Keywords ──────────────────────────────────────
        current_word_str = "".join(word_buffer).strip()
        current_sentence_str = " ".join(sentence_buffer).strip()
        
        detected_kw = is_emergency_text(current_word_str)
        if not detected_kw:
            detected_kw = is_emergency_text(current_sentence_str)
            
        if detected_kw:
            if now - last_emergency_trigger_time >= emergency_cooldown_duration:
                emergency_active = True
                emergency_keyword = detected_kw
                emergency_trigger_time = now
                emergency_language = selected_language
                last_emergency_trigger_time = now
                
                print(f"[EMERGENCY] Active! Keyword: {detected_kw}")
                
                # 1. Sound Alert (non-blocking background thread)
                trigger_sound_alert()
                
                # 2. Priority Speech (concat and speak at max volume)
                if selected_language == "Tamil":
                    text_to_translate = current_sentence_str if current_sentence_str else current_word_str
                    translated_tamil = translate_to_tamil(text_to_translate)
                    priority_text = "அவசர உதவி கோரப்பட்டுள்ளது. " + translated_tamil
                    speech_lang = "Tamil"
                else:
                    text_to_speak = current_sentence_str if current_sentence_str else current_word_str
                    priority_text = "Emergency assistance requested. " + text_to_speak
                    speech_lang = "English"
                
                tts.speak(priority_text, language=speech_lang, volume=1.0)
                
                # 3. Supabase Log (non-blocking background thread)
                db_translated = translate_to_tamil(current_sentence_str) if selected_language == "Tamil" else ""
                db_thread = threading.Thread(
                    target=save_emergency_event,
                    args=(detected_kw, current_sentence_str, db_translated, selected_language, 100.0),
                    daemon=True
                )
                db_thread.start()
                
                # Increment count
                emergency_count_today += 1
                
                # 4. Print history in console (delayed print to allow write completion)
                def delayed_history():
                    time.sleep(1.5)
                    print_emergency_history()
                threading.Thread(target=delayed_history, daemon=True).start()
                
                # 5. Future hooks
                send_sms_alert(detected_kw, current_sentence_str, selected_language)
                send_whatsapp_alert(detected_kw, current_sentence_str, selected_language)
                send_email_alert(detected_kw, current_sentence_str, selected_language)
                notify_caregiver(detected_kw, current_sentence_str, selected_language)
                loc = share_location()
                print(f"[FUTURE READY] Share location: {loc}")

        # ── Compute HUD state dict ──────────────────────────────────────
        hold_elapsed = 0.0
        is_holding = False
        if hold_timer_start is not None:
            hold_elapsed = now - hold_timer_start
            is_holding = True

        hud_state = {
            "stable_prediction": current_prediction,
            "hold_elapsed": hold_elapsed,
            "is_holding": is_holding,
            "locked_until_reset": locked_until_reset,
            "feedback_message": feedback_message,
            "emergency_active": emergency_active,
            "emergency_keyword": emergency_keyword,
            "emergency_trigger_time": emergency_trigger_time,
            "emergency_language": emergency_language,
            "emergency_count_today": emergency_count_today,
            "hand_status": hand_status,
            "hand_status_detail": hand_status_detail,
        }

        # ── FPS ─────────────────────────────────────────────────────────
        fps = 0.8 * fps + 0.2 * (1.0 / max(now - prev_time, 1e-6))
        prev_time = now

        # ── Determine translated text for display (Tamil mode) ──────────
        display_translated = ""
        if selected_language == "Tamil" and sentence_buffer:
            sentence_text = " ".join(sentence_buffer)
            display_translated = translator.translate(sentence_text)

        # ── Draw HUD ────────────────────────────────────────────────────
        draw_hud(frame, current_prediction, confidence, probabilities,
                 label_names, word_buffer, sentence_buffer, fps,
                 hand_detected, hud_state, tts.status,
                 selected_language=selected_language,
                 translated_text=display_translated)

        cv2.imshow("ASL Sign Language Recognition", frame)

        # ── Key handling ────────────────────────────────────────────────
        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), ord("Q"), 27):  # Q or ESC
            break

        elif key in (ord("c"), ord("C")):
            # Clear BOTH word buffer and sentence buffer
            word_buffer.clear()
            word_confidences.clear()
            sentence_buffer.clear()
            sentence_confidences.clear()
            last_added_letter = None
            locked_until_reset = False
            print("[CLEAR] Word + sentence buffers cleared.")

        elif key == 32:  # SPACE — finish current word and push to sentence
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                sentence_confidences.extend(word_confidences)
                print(f"[WORD] \"{current_word}\" added to sentence. "
                      f"Sentence: {' '.join(sentence_buffer)}")
            word_buffer.clear()
            word_confidences.clear()
            last_added_letter = None
            locked_until_reset = False

        elif key in (ord("l"), ord("L")):
            # Toggle between English and Tamil
            if selected_language == "English":
                selected_language = "Tamil"
                translator.target_lang = "Tamil"
                print("[LANG] Language switched to: Tamil")
            else:
                selected_language = "English"
                translator.target_lang = "English"
                print("[LANG] Language switched to: English")
            feedback_message = f"Language: {selected_language}"
            feedback_timestamp = now

        elif key == 8:  # BACKSPACE
            if word_buffer:
                removed = word_buffer.pop()
                if word_confidences:
                    word_confidences.pop()
                print(f"[BKSP] Removed '{removed}'.")
                last_added_letter = None
                locked_until_reset = False

        elif key == 13:  # ENTER — speak the sentence
            print("[DEBUG] ENTER PRESSED")
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                sentence_confidences.extend(word_confidences)
                word_buffer.clear()
                word_confidences.clear()

            if sentence_buffer:
                full_sentence = " ".join(sentence_buffer)
                print(f"[DEBUG] Text:\n{full_sentence}")

                if sentence_confidences:
                    avg_conf = (sum(sentence_confidences) / len(sentence_confidences)) * 100.0
                else:
                    avg_conf = 100.0
                avg_conf = round(avg_conf, 1)

                # Apply translation based on current language
                translated = translator.translate(full_sentence)
                tts_language = selected_language

                if selected_language == "Tamil":
                    speak_text = translated
                    if translated != full_sentence:
                        print(f"[TAMIL] Translated: {translated}")
                    else:
                        print("[TAMIL] No translation found, speaking English.")
                else:
                    speak_text = full_sentence

                spoken = tts.speak(speak_text, language=tts_language)
                print(f"[DEBUG] speak() returned:\n{spoken}")
                if spoken:
                    feedback_message = f"Speaking: {full_sentence}"
                    feedback_timestamp = now

                    # Save to Supabase with language and translation info
                    save_recognition(recognized_text=full_sentence,
                                     translated_text=translated if selected_language == "Tamil" else "",
                                     selected_language=selected_language,
                                     confidence=avg_conf)
            else:
                print("[TTS] No text available to speak.")
                feedback_message = "No text to speak"
                feedback_timestamp = now

    # ── Cleanup ─────────────────────────────────────────────────────────────
    tts.shutdown()
    hands.close()
    cap.release()
    cv2.destroyAllWindows()
    final_word = "".join(word_buffer) if word_buffer else "(empty)"
    final_sentence = " ".join(sentence_buffer) if sentence_buffer else "(empty)"
    print(f"\n[OK] Session ended.")
    print(f"     Final word:     {final_word}")
    print(f"     Final sentence: {final_sentence}")


if __name__ == "__main__":
    main()
